# Generated by Django 3.2.8 on 2022-03-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_auto_20220303_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='province',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='ward_no',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
