# Generated by Django 3.2.8 on 2022-04-04 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
