# Generated by Django 3.2.8 on 2022-04-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0009_remove_orderitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, null=True)),
                ('pres', models.ImageField(blank=b'I01\n', default='', upload_to='medicines/prescription')),
            ],
        ),
    ]
