# Generated by Django 3.2.8 on 2022-04-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0010_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='pres',
            field=models.ImageField(default='', null=True, upload_to='medicines/prescription'),
        ),
    ]
