# Generated by Django 3.2.8 on 2022-04-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0011_alter_prescription_pres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='pres',
            field=models.ImageField(default='', null=True, upload_to='medicines/prescription'),
        ),
    ]
