# Generated by Django 3.2.8 on 2022-04-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0012_auto_20220405_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='pres',
            field=models.ImageField(default='', null=True, upload_to='medicines/images'),
        ),
    ]
