# Generated by Django 3.2.8 on 2022-04-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0014_alter_shippingaddress_pres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='pres',
            new_name='image',
        ),
    ]
