# Generated by Django 3.2.8 on 2022-04-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0017_auto_20220406_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
