# Generated by Django 3.2.8 on 2022-04-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0018_auto_20220406_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(choices=[('Province 1', 'Province 1'), ('Province 2', 'Province 2'), ('Province 3', 'Province 3'), ('Province 4', 'Province 4'), ('Province 5', 'Province 5'), ('Province 6', 'Province 6'), ('Province 7', 'Province 7')], default='', max_length=50, null=True),
        ),
    ]
