# Generated by Django 3.2.8 on 2022-04-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0019_auto_20220406_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
    ]
