# Generated by Django 3.2.8 on 2022-04-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0022_auto_20220413_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='ward_no',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.IntegerField(null=True),
        ),
    ]
