# Generated by Django 3.2.8 on 2022-04-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0023_auto_20220418_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur')], default='', max_length=100, null=True),
        ),
    ]
