# Generated by Django 3.2.8 on 2022-04-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0026_auto_20220420_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='pres',
        ),
    ]
