# Generated by Django 3.2.8 on 2022-04-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0031_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
