# Generated by Django 3.2.8 on 2022-04-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0035_alter_shippingaddress_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], default='Order Received', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti Pay', 'Khalti Pay')], default='Cash On Delivery', max_length=20),
        ),
    ]
