# Generated by Django 3.2.8 on 2022-05-08 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0040_completedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorder',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicines.product'),
        ),
    ]
