# Generated by Django 3.2.8 on 2022-05-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0041_completedorder_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorder',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
