# Generated by Django 3.2.8 on 2022-05-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0042_completedorder_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='completedOrder',
        ),
    ]
