# Generated by Django 3.2.8 on 2022-05-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0044_alter_shippingaddress_pres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='pres',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Pharmacy\\static\\image\\medicines\\prescription'),
        ),
    ]
