# Generated by Django 4.1.7 on 2023-04-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0048_alter_shippingaddress_pres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='model',
        ),
    ]
