# Generated by Django 4.1.7 on 2023-04-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0049_rename_brand_product_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
