# Generated by Django 4.1.7 on 2023-04-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0050_rename_model_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=b'I01\n', default='', null=True, upload_to='medicines/images'),
        ),
    ]
