# Generated by Django 4.1.7 on 2023-04-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0051_remove_product_expiry_date_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='composition',
            new_name='genre',
        ),
    ]
