# Generated by Django 4.1.7 on 2023-04-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0053_pukar_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
