# Generated by Django 4.1.7 on 2023-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0054_product_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='Book_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='Author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
