# Generated by Django 4.1.7 on 2023-04-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0055_rename_product_name_product_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=2023),
        ),
    ]
