# Generated by Django 4.1.7 on 2023-04-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0056_alter_product_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_name',
            new_name='Book_name',
        ),
    ]
